FROM pytorch/pytorch:1.12.1-cuda11.6-cudnn8-runtime

WORKDIR /home/rym/Documents/HACKATHON

COPY . /bandwidth.py
COPY . /network.py

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

CMD ["python", "bandwidth.py"] 
